
export const RECEIVE_CARRIER_LIST = 'RECEIVE_CARRIER_LIST' // 承运商信息
export const RECEIVE_CARRIER_CAR_LIST = 'RECEIVE_CARRIER_CAR_LIST' // 承运商车辆信息
export const RECEIVE_CARRIER_DRIVER_LIST = 'RECEIVE_CARRIER_DRIVER_LIST' // 承运商司机信息
