export const RECEIVE_CLIENT_LIST = 'RECEIVE_CLIENT_LIST' // 公司客户信息列表
export const RECEIVE_CONSIGNERS_LIST = 'RECEIVE_CONSIGNERS_LIST' // 发货方列表
export const RECEIVE_ADDRESS_LIST = 'RECEIVE_ADDRESS_LIST' // 发货地址列表
export const RECEIVE_CONSIGNEES_LIST = 'RECEIVE_CONSIGNEES_LIST' // 收货方列表
export const RECEIVE_CARGO_LIST = 'RECEIVE_CARGO_LIST' // 已维护的货物列表
export const RECEIVE_CONSIGNER_CARGO_LIST = 'RECEIVE_CONSIGNER_CARGO_LIST' // 用户正在编辑的货物信息列表

export const APPEND_CONSIGNER_CARGO = 'APPEND_CONSIGNER_CARGO' // 添加货物
export const REMOVE_CONSIGNER_CARGO = 'REMOVE_CONSIGNER_CARGO' // 删除货物
export const UPDATE_CONSIGNER_CARGO = 'UPDATE_CONSIGNER_CARGO' // 更新货物部分数据
export const UPDATE_FULL_CONSIGNER_CARGO = 'UPDATE_FULL_CONSIGNER_CARGO' // 全量替换货物
export const CLEAR_CONSIGNER_CARGO_LIST = 'CLEAR_CONSIGNER_CARGO_LIST' // 清除编辑的货物列表

export const RECEIVE_ORDER_DETAIL = 'RECEIVE_ORDER_DETAIL' // 订单详情

export const RECEIVE_CARRIER_LIST = 'RECEIVE_CARRIER_LIST' // 承运商信息
export const RECEIVE_CARRIER_CAR_LIST = 'RECEIVE_CARRIER_CAR_LIST' // 承运商车辆信息
export const RECEIVE_CARRIER_DRIVER_LIST = 'RECEIVE_CARRIER_DRIVER_LIST' // 承运商司机信息
export const RECEIVE_TRANSFEREE_LIST = 'RECEIVE_TRANSFEREE_LIST' // 外转方信息
