export const RECEIVE_CLIENT_LIST = 'RECEIVE_CLIENT_LIST'
export const RECEIVE_CONSIGNERS_LIST = 'RECEIVE_CONSIGNERS_LIST'
export const RECEIVE_ADDRESS_LIST = 'RECEIVE_ADDRESS_LIST'
export const RECEIVE_CONSIGNEES_LIST = 'RECEIVE_CONSIGNEES_LIST'
export const RECEIVE_CARGO_LIST = 'RECEIVE_CARGO_LIST'
export const RECEIVE_CONSIGNER_CARGO_LIST = 'RECEIVE_CONSIGNER_CARGO_LIST'

export const APPEND_CONSIGNER_CARGO = 'APPEND_CONSIGNER_CARGO'
export const REMOVE_CONSIGNER_CARGO = 'REMOVE_CONSIGNER_CARGO'
export const UPDATE_CONSIGNER_CARGO = 'UPDATE_CONSIGNER_CARGO'
export const UPDATE_FULL_CONSIGNER_CARGO = 'UPDATE_FULL_CONSIGNER_CARGO'
export const CLEAR_CONSIGNER_CARGO_LIST = 'CLEAR_CONSIGNER_CARGO_LIST'

export const RECEIVE_ORDER_DETAIL = 'RECEIVE_ORDER_DETAIL'

export const RECEIVE_CARRIER_LIST = 'RECEIVE_CARRIER_LIST' // 承运商信息
export const RECEIVE_CARRIER_CAR_LIST = 'RECEIVE_CARRIER_CAR_LIST' // 承运商车辆信息
export const RECEIVE_CARRIER_DRIVER_LIST = 'RECEIVE_CARRIER_DRIVER_LIST' // 承运商司机信息
